id: DAEB7A195
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-18T05:31:08+00:00'
last_modified: '2022-05-29T08:49:07.711473+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    b777:
      image_group_id: I1PD95924
      title: ཆོས་མངོན་པའི་མཛོད་ཀྱི་བཤད་པ།
      total_pages: 1433
      order: 79
      base_file: b777.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
