id: P79F4D9EF
initial_creation_type: ocr
source_metadata:
  volumes:
    ecccdbb20cd84bc194ace781a007d116:
      base_file: v079.txt
      image_group_id: I1PD95924
      title: ཆོས་མངོན་པའི་མཛོད་ཀྱི་བཤད་པ།
      total_pages: 1433
      volume_number: 79
