id: P79F4D9EF
initial_creation_type: ocr
source_metadata:
  volumes:
    51d05e7953064a7db8691e638d32ea97:
      base_file: v079.txt
      image_group_id: I1PD95924
      title: ཆོས་མངོན་པའི་མཛོད་ཀྱི་བཤད་པ།
      total_pages: 1433
      volume_number: 79
